variable "client_s3_policy_name" {}
variable "client_s3_role_name" {}
variable "client_ec2_s3_role_name" {}
variable "client_ec2_s3_policy_name" {}
variable "client_s3_role_association_db_identifier" {}
variable "client_ecs_service_policy" {}
variable "client_ecs_service_role" {}
variable "client_data_bucket" {}
variable "db_cluster_identifier" {}